---

- hosts: "{{ passed_in_hosts }}"
  become: yes
  remote_user: ec2-user
  become_user: root
  tasks:
    - name: Install git
      yum:
        name: git
        state: present
    - name: Install apache
      yum:
        name: httpd
        state: present
    - name: Start and enable apache
      service:
        name: httpd
        state: started
        enabled: yes
